# Generated by Django 5.1.5 on 2025-01-29 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название организационной структуры')),
            ],
            options={
                'verbose_name': 'Организационная структура',
                'verbose_name_plural': 'Организационные структуры',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название компании')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='companies.structure', verbose_name='Организационная структура')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='StructureMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=64, verbose_name='Позиция в команде')),
                ('role', models.CharField(max_length=64, verbose_name='Роль в команде')),
                ('subordinates', models.CharField(max_length=64, null=True, verbose_name='Непосредственные начальники')),
                ('bosses', models.CharField(max_length=64, null=True, verbose_name='Непосредственные подчиненные')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.structure', verbose_name='Название организационной структуры')),
            ],
            options={
                'verbose_name': 'Член организационной структуры',
                'verbose_name_plural': 'Члены организационной структуры',
            },
        ),
    ]
