# Generated by Django 5.1.5 on 2025-01-29 18:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Время начала встречи')),
                ('end_at', models.DateTimeField(verbose_name='Время завершения встречи')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.profile', verbose_name='Организатор встречи')),
                ('participants', models.ManyToManyField(to='accounts.profile', verbose_name='Участники встречи')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок новости')),
                ('content', models.TextField(verbose_name='Содержание новости')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Автор новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('deadline', models.DateTimeField(verbose_name='Deadline задачи')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_task', to='accounts.profile', verbose_name='Создатель задачи')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='accounts.profile', verbose_name='Исполнитель задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_meeting', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Соблюдение сроков задачи')),
                ('completeness', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Полнота выполнения задачи')),
                ('quality', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Качество выполнения задачи')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Оценка задачи',
                'verbose_name_plural': 'Оценки задач',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Название дела')),
                ('start_at', models.DateTimeField(verbose_name='Время начала дела')),
                ('end_at', models.DateTimeField(verbose_name='Время окончания дела')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='accounts.profile', verbose_name='Владелец зарезервированного времени')),
            ],
            options={
                'verbose_name': 'Зарезервированное время для дел',
                'verbose_name_plural': 'Зарезервированное время для дел',
                'constraints': [models.UniqueConstraint(fields=('owner', 'start_at', 'end_at'), name='Unique calendar constraint')],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Выполняется'), ('DEFERRED', 'Отложено'), ('FINISHED', 'Выполнено')], default='PENDING', max_length=16, verbose_name='Статус задачи')),
                ('comment', models.CharField(blank=True, max_length=128, verbose_name='Комментарий к задаче')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
                'constraints': [models.UniqueConstraint(fields=('task', 'status'), name='Unique task constraint')],
            },
        ),
    ]
