# Generated by Django 5.1.5 on 2025-02-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название дела'),
        ),
    ]
