# Generated by Django 5.1.5 on 2025-02-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_meeting_organizer_alter_meeting_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название задачи'),
        ),
    ]
