# Generated by Django 5.1.5 on 2025-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_position'),
        ('activities', '0005_alter_task_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskstatus',
            name='Unique task constraint',
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название задачи'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('name', 'assigned_to'), name='Unique task constraint'),
        ),
        migrations.AddConstraint(
            model_name='taskstatus',
            constraint=models.UniqueConstraint(fields=('task', 'status'), name='Unique task status constraint'),
        ),
    ]
