# Generated by Django 5.1.5 on 2025-02-04 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_remove_taskstatus_unique_task_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskestimation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата выставления оценки'),
            preserve_default=False,
        ),
    ]
