# Generated by Django 5.1.5 on 2025-01-29 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('EMPLOYEE', 'Подчиненный'), ('MANAGER', 'Менеджер')], default='EMPLOYEE', max_length=32, verbose_name='Должность')),
                ('is_administrator', models.BooleanField(default=False, verbose_name='Администратор?')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='companies.company', verbose_name='Компания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
