# Generated by Django 5.1.5 on 2025-02-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('EMPLOYEE', 'Подчиненный'), ('MANAGER', 'Менеджер'), ('BOSS', 'Генеральный Менеджер')], default='EMPLOYEE', max_length=32, verbose_name='Должность'),
        ),
    ]
